### ISSUE TITLE
RCAT button on tools.riverscapes.net directs to the wrong page

### ISSUE THREAD

**Issue by dominique-shore** [Riverscapes/riverscapes-gatsby#21]
The RCAT button on the homepage of [tools.riverscapes.net](https://tools.riverscapes.net/) directs you to https://tools.riverscapes.net/anthro/, not https://tools.riverscapes.net/rcat/. 

Please let me know if this is the wrong repo for this issue - still learning! Thanks!

**Comment by dominique-shore** [comment]
@MattReimer can you take a look? I don't seem to have 'assign' access on this repo.

**Comment by philipbaileynar** [comment]
Good news.... I've fixed the link.

Bad news... no documentation at the correct URL either :-(
